
name: Inputs

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Enter Input Message'
        required: true

jobs:
  input_display:
    runs-on: ubuntu-latest
    steps:
      - name: Input Display Message
        run: echo "${{ github.event.inputs.message }}"

