name: Echo Environment Secret

on:
  workflow_dispatch:
    inputs:
      inputenv:
        description: 'Choose an environment'
        required: true
        default: 'My_Environmnet'


jobs:
  echo_url:
    runs-on: ubuntu-latest
    environment: 
            name: ${{ github.event.inputs.inputenv }}
    steps:
      - name: Echo Environment Variable
        run: echo "The Value is $URL"
        env:
          URL: ${{ secrets.URL }}
